source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in peatio-ripple.gemspec
gemspec

gem 'peatio', git: 'https://github.com/pranjal0819/peatio-core', branch: 'mainline'
